/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/F3VfKtilXLs
 */
import { Label } from "@/components/ui/label";
import { Input } from "@/components/ui/input";
import Link from "next/link";
import { Button } from "@/components/ui/button";

function Navbar() {
  return (
    <>
      <nav className="fixed top-0 left-0 right-0 z-10 bg-white dark:bg-gray-800 shadow-md">
        <div className="container mx-auto px-6 sm:px-12 flex items-center justify-between h-16">
          <div className="flex items-center">
            <div className="hidden md:block">
              <h1 className="text-2xl font-bold text-gray-700 dark:text-gray-200">
                Your App
              </h1>
            </div>
            <div className="md:hidden">
              <button className="text-gray-500 dark:text-gray-200 hover:text-gray-600 dark:hover:text-gray-400">
                <svg className="w-6 h-6" fill="currentColor" viewBox="0 20">
                  <path
                    clipRule="evenodd"
                    d="M3 5a1 1 0 011-1h12a1 110 2H4a1 01-1-1zm0 6a1 01-1-1zm1 100 2h12a1 100-2H4z"
                    fillRule="evenodd"
                  />
                </svg>
              </button>
            </div>
          </div>
          <div className="flex items-center">
            <button className="text-gray-500 dark:text-gray-200 hover:text-gray-600 dark:hover:text-gray-400">
              <svg className="w-6 h-6" fill="currentColor" viewBox="0 24">
                <path d="M0 0h24v24H0z" fill="none" stroke="none" />
                <circle cx="12" cy="12" r="3" />
                <line x1="12" x2="12" y1="5" y2="2" />
                <line x1="12" x2="12" y1="19" y2="22" />
                <line x1="4.22" x2="5.64" y1="4.22" y2="5.64" />
                <line x1="18.36" x2="19.78" y1="18.36" y2="19.78" />
                <line x1="1" x2="4" y1="12" y2="12" />
                <line x1="20" x2="23" y1="12" y2="12" />
                <line x1="4.22" x2="5.64" y1="19.78" y2="18.36" />
                <line x1="18.36" x2="19.78" y1="5.64" y2="4.22" />
              </svg>
            </button>
          </div>
        </div>
      </nav>
    </>
  );
}

export function LoginPage() {
  return (
    <div
      key="1"
      className="flex flex-col items-center justify-center min-h-screen bg-gray-100 dark:bg-gray-900"
    >
      <Navbar />
      <div className="space-y-6 mt-10 p-4">
        <div className="space-y-2 text-center">
          <h1 className="text-3xl font-bold">Login</h1>
          <p className="text-gray-500 dark:text-gray-400 max-w-sm mx-auto">
            Enter your username and password to login to your account
          </p>
        </div>
        <div className="w-full max-w-sm space-y-4">
          <div className="space-y-2">
            <Label htmlFor="username">Username</Label>
            <Input id="username" placeholder="Username" required />
          </div>
          <div className="space-y-2">
            <div className="flex items-center">
              <Label htmlFor="password">Password</Label>
              <Link className="ml-auto inline-block text-sm underline" href="#">
                Forgot your password?
              </Link>
            </div>
            <Input id="password" required type="password" />
          </div>
          <Button className="w-full" type="submit">
            Login
          </Button>
        </div>
      </div>
    </div>
  );
}
